config/routes.rb
Depot::Application.routes.draw do
  
  root :to => 'finder#index', :as => 'index'
  
  controller :finder do
	  get   "index" => :index
    get   "result" => :result
    get   "result\/:id" => :old_result
    post  "index" => :find
    post  "login" => :entering
    post  "logout" => :leaving
	end  

end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  # GET /index
  def index
    @member = Member[session[:member_id]] if session[:member_id]
  end

  # вход в систему, под указанным юзером
  def entering
    session[:member_id] = Member.find(:name => params[:member]).first.id if Member.find(:name => params[:member]).first || Member.create(:name => params[:member]).id
    redirect_to index_path
  end

  # выход из системы
  def leaving
    session[:member_id] = nil
    redirect_to index_path
  end

  # GET /result/id
  # показывает результат, основанный на id
  def old_result
    @res = Result[params[:id]]
    session[:result_id] = @res.id
    render(:result)
  end

  # GET /result
  # создаёт новый результат и перенаправляет в old_result
  def result
    member = Member[session[:member_id]] if session[:member_id]
    res = Result.create(:member => member,
                        :search_params => params,
                        :search_at => Time.now,
                        )
    session[:result_id] = res.id
    redirect_to :action => :old_result, :id => res.id
  end

  # AJAX запрос, POST /index
  # метод поиска
  def find
    # получаем переменную результата, в которую будем записывать найденные перелёты
    res = Result[session[:result_id]]
    @results = []

    # Если данный запрос уже был обработан, возвращается его результат из БД
    data = Ohm.redis.get("results:#{res.id}")
    if data
      @results = Marshal.load(data)
      return
    end

    # В инстанс переменную записывается результат выполнения метода find_flys
    #   с параметрами поиска
    @results << find_flys(Aeroport[res.search_params["departure"]],
                          convert_date(res.search_params["departure_date"],0),
                          Aeroport[res.search_params["arrival"]])

    # Если указано продолжение пути - в результат дописывается второй перелёт
    if res.search_params["second_route"]
      @results << find_flys(Aeroport[res.search_params["departure_2"]],
                            convert_date(res.search_params["departure_date_2"],0),
                            Aeroport[res.search_params["arrival_2"]])
    end

    # Запись в БД результат поиска
    Ohm.redis.set("results:#{res.id}", Marshal.dump(@results))

    # рендер яваскрипта
    respond_to do |format|
      format.js
    end
  end

  private

  # хелпер парсинга параметров поиска
  def parsing_params(fly, par)
    if par[:format] == :html
      (params[:changes].to_i + 1) >= fly.number_of_tracks &&
        params[:price].to_f >= fly.total_cost &&
        (params[:pend_hours].to_i*3600 + params[:pend_minutes].to_i*60) >=
          fly.total_pending &&
        (params[:hours].to_i*3600 + params[:days].to_i*86400) >=
          fly.total_time
    elsif par[:format] == :js
      (params[:select_changes].to_i + 1) >= fly.number_of_tracks &&
        params[:select_price].to_f >= fly.total_cost &&
        (params[:select_pend_hours].to_i*3600 + params[:select_pend_minutes].to_i*60) >=
          fly.total_pending &&
        (params[:select_hours].to_i*3600 + params[:select_days].to_i*86400) >=
          fly.total_time
    end
  end

  # хелпер конвертирования даты
  def convert_date(date, difference=0)
    d = date.map{|key,value| value.to_i}
    (d[-1] = d[-1] - 1) until Date.valid_date?(*d)
    date = Date.new(*d)
    date+difference
  end

  # основной метод поиска перелётов
  def find_flys(dep_port, dep_date, arr_port)
    # максимальное число часов между перелётами в одном маршруте
    max_pending_hours = 24

    # переменная маршрута, класса Route с местом отправления и местом назначения
    route = Route.new(dep_port.name,arr_port.name)

    # Поиск прямых перелётов из точки отправления в точку назначения
    route.flys = (Ohm.redis.zrangebyscore("from:#{dep_port.id}:to:#{arr_port.id}",
      dep_date.to_time.to_i, (dep_date+1).to_time.to_i) ||
    []).map do |par|
      ff = FullFly.new
      ff + Track.new(par)
    end

    # Поиск перелётов с одной пересадкой.
    # Логика: Ищем все аэропорты, перелёты в которые возможно сделать из места
    #   убытия. В каждом найденном аэропорту ищутся:
    #   1. Перелёты из места убытия в текущий аэропорт, в заданную дату.
    #   2. Перелёты из текущего аэропорта в место назначения,
    #     в заданную дату плюс от 5 (минимальное время полёта + ожидания) до 38
    #     (14 максимальное время одного полёта + 24 максимальное время ожидания
    #     между перелётами)
    #   Затем значения массивов сравниваются, и добавляются как возможный вариант,
    #     если подходят условиям (время прибытия первого перелёта < времени
    #     убытия второго перелёта на время от часа до 24 часов)
    Ohm.redis.smembers("allRoutesFrom:#{dep_port.id}").each do |id|
      # Создание массива вылетов из места убытия
      temp_dep =  (Ohm.redis.zrangebyscore("from:#{dep_port.id}:to:#{id}",
        dep_date.to_time.to_i, (dep_date+1).to_time.to_i) ||
      [])

      # Создание массива прилётов в место назначения
      temp_arr =  (Ohm.redis.zrangebyscore("from:#{id}:to:#{arr_port.id}",
        dep_date.to_time.to_i + 60*60*(4+1),
        (dep_date+1).to_time.to_i + 60*60*14 + 60*60*max_pending_hours) ||
      [])
      # Проверка условий перелётов
      temp_dep.each do |first|
        temp_arr.each do |last|
          tr_dep = Track.new(first)
          tr_arr = Track.new(last)
          if (tr_dep.arr_time + 60*60 < tr_arr.dep_time &&
            tr_dep.arr_time + 60*60*max_pending_hours > tr_arr.dep_time)

            ff = FullFly.new
            ff + tr_dep
            ff + tr_arr
            route + ff
          end # if
        end   # temp_arr.each
      end     # temp_dep.each
    end       # smembers.each

    # Поиск перелётов с 2-мя пересадками. Принцип тот же, только ищется
    #   перелёты во все возможные места из пункта убытия, и все возможные места
    #   откуда можно добраться в конечную точку. И между ними ищется подходящий
    #   перелёт.

    Ohm.redis.smembers("allRoutesFrom:#{dep_port.id}").each do |first_id|
      # Пропускаем аэропорт если он конечная точка, т.к. это уже учли в перелётах
      #   без пересадки
      next if first_id == arr_port.id
      # Все возможные перелёты из стартовой точки в текущий аэропорт
      first_temp_arr = (Ohm.redis.zrangebyscore("from:#{dep_port.id}:to:#{first_id}",
        dep_date.to_time.to_i,(dep_date+1).to_time.to_i) ||
      []).map{|str| Track.new(str)}

      # Все аэропорты, из которых возможны перелёты в конечную точку
      Ohm.redis.smembers("allRoutesTo:#{arr_port.id}").each do |last_id|
        # Пропускаем аэропорт если пенкт отправления в конечную точку -
        #   место отправления (это учли в перелётах без пересадки) или
        #   место возможного перелёта из места отправления (это учли
        #   в перелёте с 1 пересадкой)
        next if last_id == dep_port.id || last_id == first_id
          # Все возможные перелёты в конечную точку
        last_temp_arr = (Ohm.redis.zrangebyscore("from:#{last_id}:to:#{arr_port.id}",
          (dep_date+1).to_time.to_i + 60*60*12,
          (dep_date+4).to_time.to_i) ||
        []).map{|str| Track.new(str)}

        # средний перелёт - между 2-мя пересадками
        middle_temp_arr = (Ohm.redis.zrangebyscore("from:#{first_id}:to:#{last_id}",
          (dep_date).to_time.to_i + 60*60*5,
          (dep_date+1).to_time.to_i + 60*60*max_pending_hours) ||
        []).map{|str| Track.new(str)}

        # проверка условий. Такие же как с 1 пересадкой
        first_temp_arr.each do |first|
          last_temp_arr.each do |last|
            middle_temp_arr.each do |middle|
              if (middle.arr_time + 60*60 < last.dep_time  &&
                first.arr_time + 60*60 < middle.dep_time &&
                first.arr_time + 60*60*max_pending_hours > middle.dep_time &&
                middle.arr_time + 60*60*max_pending_hours > last.dep_time)

                ff = FullFly.new
                ff + first
                ff + middle
                ff + last
                route + ff
              end # if
            end   # middle_temp_arr.each
          end     # last_temp_arr.each
        end       # first_temp_arr.each
      end         # smembers airports with flys to arrival place
    end           # smembers airports with flys from dep place
    # сортируем по общей стоимости
    route.flys.sort_by!{|fly| fly.total_cost}
    route
  end

end

app/helpers/finder_helper.rb
module FinderHelper
  def seconds_to_time(sec)
    #debugger
    str=""
    days = sec/86400
    hours = (sec - days*86400)/3600
    minutes = (sec - days*86400 - hours*3600)/60
    if days > 0
      str += days.to_s + "d." 
    end
    str += " " + hours.to_s + "h. " + minutes.to_s + "m."
  end
  
  def generate_link(res)
    #debugger
    link_to("From: " + Aeroport[res.search_params["departure"]].name + " To: " + Aeroport[res.search_params["arrival"]].name + " at: " + convert_date(res.search_params["departure_date"],0).to_s + " (searched at:" + res.search_at.strftime("%y.%m.%d %H:%M )"),
    "result/#{res.id}")
  end
  
  def index_link
    if session[:member_id]
      link_to 'Recent searches', index_path 
    else
      link_to 'New search', index_path 
    end
  end
  
  private
  	  
	  def convert_date(date, difference=0)
      d = date.map{|key,value| value.to_i}
      (d[-1] = d[-1] - 1) until Date.valid_date?(*d) 
      date = Date.new(*d)
      date+difference
    end
end

app/views/finder/_find_form.html.erb
<%= form_tag result_path, :class => 'form', :method => :get do %>
  <div id="places">

      <div id="aeroport">
        <%= label_tag :departure, "Место отбытия: " %>
        <%= select_tag  :departure,
                      options_for_select(Aeroport.names)%>
      </div>                  
      
      <div id="aeroport">
        <%= label_tag :arrival, "Место прибытия: " %>
        <%= select_tag  :arrival,
                        options_for_select(Aeroport.names)%>
      </div>
      
      <div id="date">
        <%= label_tag :departure_date, "Дата отправления: " %>
        <%= date_select(:departure_date, Date.today) %><br />
       </div>
   </div>
 
  <div id="continue_route" style="display: none">
    <br />
    <div id="departure">
      <div id="aeroport">
        <%= label_tag :departure_2, "Место отбытия: " %>
        <%= select_tag  :departure_2,
                      options_for_select(Aeroport.names)%>
      </div>                  

      <div id="aeroport">
        <%= label_tag :arrival_2, "Место прибытия: " %>
        <%= select_tag  :arrival_2,
                        options_for_select(Aeroport.names)%>
      </div>
            
      <div id="date">
        <%= label_tag :departure_date_2, "Дата отправления: " %>
        <%= date_select(:departure_date_2, Date.today() + 7.days) %><br />
      </div>
    </div>
  </div>
  <%= check_box_tag(:second_route, '',false, :style => "display: none") %>
  <%= content_tag("div", :id => "continue",:onclick =>"$('#continue_route').slideDown('slow');$('#cancel_continue').show();$('#continue').hide();$('#second_route').attr('checked',true);") do%>
   <h3>Продолжить путь</h3>
  <% end %>
    <%= content_tag("div", :style => "display: none", :id => "cancel_continue",:onclick =>"$('#continue_route').slideUp('slow');$('#continue').show();$('#cancel_continue').hide();$('#second_route').attr('checked',false);") do%>
   <h3>Отменить продолжение пути</h3>
  <% end %>
  <%= submit_tag("Найти")%>
<%end%>

app/views/finder/_recent_search.html.erb
<%= generate_link(recent_search) %> <br />

app/views/finder/_result.html.erb
<% @results.each_with_index do |route_member, route_idx|%>
  <%= render(:partial => "route", :object => route_member, :locals => {:indx => route_idx})%>
<% end %>

app/views/finder/_route.html.erb
<%= content_tag("div", :id => "route#{indx}", :style => "width: 45%; float: #{indx == 0 ? 'left' : 'right'}") do%>  
  <h1>Перелёты (из <%=route.departure%> в <%=route.arrival%>):</h1>
  <% unless route.flys.count == 0 %>
    <% route.flys.each_with_index do |full_fly, ff_idx|%>
      <%= content_tag("div" ,:class => "full_fly") do%>
        <span id="track_count" style="display: none"><%= full_fly.tracks.count-1 %></span>
        <% full_fly.tracks.each do |track| %>
          <%= content_tag("div" ,:style => "display:none", :class => "track_#{indx}_#{ff_idx}",:onclick =>"$('.track_#{indx}_#{ff_idx}').slideUp('fast');") do%>  
            <% unless track.pending_time == 0%>
              Время ожидания: <%= seconds_to_time(track.pending_time)%><br />
            <% end %>
            Из: <%= track.dep_place%><br />
            В   <%= Time.at(track.dep_time).strftime("%y.%m.%d %H:%M")%><br />
            В:  <%= track.arr_place%><br /> 
            К   <%= Time.at(track.arr_time).strftime("%y.%m.%d %H:%M")%><br />
            Стоимость: <%= track.cost.to_i%><br />
            Авиакомпания: <%= track.company%><br /><br />
          <% end%>
        <% end %>
        <%= content_tag("div", :id => "summary_#{indx}_#{ff_idx}",:onclick =>"$('.track_#{indx}_#{ff_idx}').slideDown('slow');") do%>
          Общая стоимость: <span id="price"><%= full_fly.total_cost%></span><br />
          <% unless full_fly.total_pending_time == 0%>
            Общее время ожидания: <%= seconds_to_time(full_fly.total_pending_time)%><br />
            <span id="total_pending_time" style="display: none"><%= full_fly.total_pending_time %></span>
          <% end %>
          Общее время в пути: <%= seconds_to_time(full_fly.total_time)%>
          <span id="total_time" style="display: none"><%= full_fly.total_time %></span>
          <hr /><br /><br />
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    Извините, по Вашему запросу ничего не найдено. Попробуйте изменить параметры поиска
  <% end %>
<% end %>

app/views/finder/_select_form.html.erb
<%= form_tag  index_path, :class => 'form', :onchange => "select();" do %>
  <div id="places">
    <div id="changes">
      <%= label_tag :select_changes_min, "Количество пересадок: " %><br />
      <%= label_tag :select_changes_min, "От: " %>
      <%= select_tag  :select_changes_min,
                      options_for_select(0..2, 0)%>
      <%= label_tag :select_changes_max, "До: " %>
      <%= select_tag  :select_changes_max,
                      options_for_select(0..2, 2)%><br /><br />
    </div>
    
    
    <div id="arrival">
      <div id="price">
        <%= label_tag :select_price_min, "Цена (руб.)" %><br />
        <%= label_tag :select_price_min, "От: " %>
        <%= text_field_tag  :select_price_min, "", :size => 5%>
        <%= label_tag :select_price_max, "До: " %>
        <%= text_field_tag  :select_price_max, "" , :size =>5%><br /><br />
      </div>
      
      <div id="max_time">
        <%= label_tag :select_days_min, "Время в пути: " %> <br />
        <%= label_tag :select_days_min, "От: " %>
        <%= label_tag :select_days_min, "Дней: " %>
        <%= select_tag  :select_days_min,
                      options_for_select(0..3)%>
        <%= label_tag :select_hours_min, "Часов: " %>
        <%= select_tag  :select_hours_min,
                      options_for_select(0..24)%><br />
        <%= label_tag :select_days_max, "До: " %>
        <%= label_tag :select_days_max, "Дней: " %>
        <%= select_tag  :select_days_max,
                      options_for_select(0..3)%>
        <%= label_tag :select_hours_max, "Часов: " %>
        <%= select_tag  :select_hours_max,
                      options_for_select(0..24)%><br /><br />
      </div>
      
      <div id="pending">
        
        <%= label_tag :з, "Время ожидания: " %> <br />
        <%= label_tag :select_pend_days_min, "От: дней: " %>
        <%= select_tag  :select_pend_days_min,
                      options_for_select(0..1)%>
        <%= label_tag :select_pend_hours_min, "часов: " %>
        <%= select_tag  :select_pend_hours_min,
                      options_for_select(0..24)%><br />
        <%= label_tag :select_pend_days_max, "До: дней: " %>
        <%= select_tag  :select_pend_days_max,
                      options_for_select(0..1)%>
        <%= label_tag :select_pend_hours_max, "часов: " %>
        <%= select_tag  :select_pend_hours_max,
                      options_for_select(0..24)%>
    
      </div>
      
    </div>
  </div>
<%end%>

app/views/finder/filter.html.erb
<h1>Finder#filter</h1>
<p>Find me in app/views/finder/filter.html.erb</p>

app/views/finder/filtering.js.erb
	unfading();
	$('#result').slideUp("fast");
  
	$('#result').slideDown("slow");	

app/views/finder/find.html.erb
<%= render(find_form)%>

app/views/finder/find.js.erb
	unfading();
	$('#result').slideUp("fast");
  $('#result').html("<%= escape_javascript render(:partial => "result")%>");
	$('#select_price_min').attr("value","<%= @results.map{|route| route.min_price}.min %>");
	$('#select_price_max').attr("value","<%= @results.inject(@results.first.max_price){|max, route|route.max_price ? (max < route.max_price ? route.max_price : max) : max} %>");
	
	$('#select_days_min').attr("value","<%= @results.inject(@results.first.min_total_days){|min, route| min > route.min_total_days ? route.min_total_days : min} %>");
	$('#select_hours_min').attr("value","<%= @results.inject(@results.first.min_total_hours){|min, route| min > route.min_total_hours ? route.min_total_hours : min} %>");
	
	$('#select_days_max').attr("value","<%= @results.inject(@results.first.max_total_days){|max, route| max < route.max_total_days ? route.max_total_days : max} %>");
	$('#select_hours_max').attr("value","<%= @results.inject(@results.first.max_total_hours){|max, route| max < route.max_total_hours ? route.max_total_hours : max} %>");
	
	$('#select_pend_days_min').attr("value","<%= @results.inject(@results.first.min_pending_days){|min, route| min > route.min_pending_days ? route.min_pending_days : min} %>");
	$('#select_pend_hours_min').attr("value","<%= @results.inject(@results.first.min_pending_hours){|min, route| min > route.min_pending_hours ? route.min_pending_hours : min} %>");
	
	$('#select_pend_days_max').attr("value","<%= @results.inject(@results.first.max_pending_days){|max, route| max < route.max_pending_days ? route.max_pending_days : max} %>");
	$('#select_pend_hours_max').attr("value","<%= @results.inject(@results.first.max_pending_hours){|max, route| max < route.max_pending_hours ? route.max_pending_hours : max} %>");
	
	$('#select_changes_min').attr("value","0");
	$('#select_changes_max').attr("value","2");
	
	$('#result').slideDown("slow");	

app/views/finder/index.html.erb
<%= render(:partial => "find_form")%>


<% if @member && (@member.results.each{}.count != 0) %>
  <h1>Ваши недавние поиски:</h1>
  <% @member.results.each do |result|%>
    <%= render(:partial => "recent_search", :object => result) %>
  <% end %>
<% end %>

app/views/finder/result.html.erb
<%= index_link %>

<div id="result">
</div>
<%= button_to "res", {:action => :find}, :style => "display: none", :id =>"find_result", :remote => true%>
<%= javascript_tag %Q|
  $(document).ready(function(){
    fading();
    $('#find_result').click();
  });|%>