config/routes.rb
Depot::Application.routes.draw do
  
  root :to => 'finder#index', :as => 'index'
  
  controller :finder do
	  get   "index" => :index
    get   "result" => :result
    get   "result\/:id" => :old_result
    post  "index" => :find
    post  "login" => :entering
    post  "logout" => :leaving
	end  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Depot</title>
  	<%= stylesheet_link_tag    "finder", :media => "all" %>
  	<%= stylesheet_link_tag    "scaffolds" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "modal" %>
  	<%= csrf_meta_tags %>
	</head>
	<body id="store">
		<div id="banner">
			<div id="logo">
				<%= Time.now.strftime("%y.%m.%d %H:%M:%S")%>
			</div>
			<%= image_tag("rails.png") %>
			<%= link_to "Flight finder", index_url %>
		    <% unless session[:member_id]%>
			  <%= form_tag login_path, :class => 'login' do%>
		      <%= label_tag :member, "Имя: " %>
          <%= text_field_tag  :member %>
	        <%= submit_tag 'Войти' %>
		    <% end %>
	    <% else %>
		    <%= form_tag logout_path, :class => 'login' do%>
		      Привет, <%= Member[session[:member_id]].name%>
	        <%= submit_tag 'выйти' %>
		    <% end %>
		  <% end %>
		</div>
		<div id="columns">
			<div id="side">
				<% if @res%>	
				  <%= content_tag("div", :id => "select_form") do%>
						<%= render :partial => "finder/select_form" %>
					<%end%>
				<%end%>
			</div>
			<div id="main">
				<%= yield %>
 			</div>
 		</div>
 		<div id="searching" style="display: none">
      <h2>Идёт поиск результатов, пожалуйста, подождите...<h2>
    </div>
 		<div id="mask"></div>  
	</body>
</html>

app/views/layouts/Копия application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Depot</title>
  	<%= stylesheet_link_tag    "depot", :media => "all" %>
  	<%= stylesheet_link_tag    "scaffolds" %>
  	<%= javascript_include_tag "application" %>
  	<%= auto_discovery_link_tag(:atom, products_url(:format => 'atom' )) %>
  	<%= csrf_meta_tags %>
	</head>
	<body id="store">
		<div id="banner">
			<div id="logo">
				<%= Time.now.strftime("%y.%m.%d %H:%M:%S")%>
			</div>
			<%= image_tag("logo.png") %>
			<%= link_to "#{page_title}", store_url %>
		  <%= form_tag index_path, :class => 'locale' do%>
		    <%= label_tag :member, "Имя: " %>
        <%= text_field_tag  :member %>
		    <%=# select_tag  'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()' %>
		    <%= submit_tag 'Войти' %>
		    <%=# javascript_tag "$('.locale input').attr(\"style\", \"display: none\")"%>
		  <% end %>
			
		</div>
		<div id="columns">
			<div id="side">
				<% if @cart%>	<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do%>
						<%= render @cart %>
					<%end%>
				<%end%>
				<a href="http://www...."><%= t('.home')%></a><br />
				<a href="http://www..../faq"><%= t('.questions')%></a><br />
				<a href="http://www..../news"><%= t('.news')%></a><br />
				<a href="http://www..../contact"><%= t('.contact')%></a><br />
				<% if session[:user_id] %>
					<br />
					<%= link_to 'Orders', orders_path %> <br />
					<%= link_to 'Products', products_path %> <br />
					<%= link_to 'Users', users_path %> <br />
					<br />
					<%= button_to "Logout", logout_url, :method => :delete%>
				<% end %>
			</div>
			<div id="main">
				<%= yield %>
 			</div>
 		</div>
	</body>
</html>